# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FipeCarsMVVMExercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!


  # Pods for FipeCarsMVVMExercise
  pod 'Alamofire'

  target 'FipeCarsMVVMExerciseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FipeCarsMVVMExerciseUITests' do
    # Pods for testing
  end

end
